### PR TITLE
Remove libdrs

### PR DESCRIPTION
**Pull request by jasonb5**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jasonb5** [comment]
@conda-forge-admin, please rerender

**Review by doutriaux1 — APPROVED** [review]
@jasonb5 this looks good. I "Think" I had to build libcdms twice once w/o fortran and once with it. I don't remmber the order, but we only need one now.

**Comment by jasonb5** [comment]
@doutriaux1 This builds one package, the two separate packages may have been from before moving to conda-forge.

**Comment by doutriaux1** [comment]
> 

@jasonb5 my bad it was libdrs that had to be built w and w/o fortran: https://github.com/conda-forge/libdrs_f-feedstock https://github.com/conda-forge/libdrs-feedstock

**Comment by jasonb5** [comment]
Aww ok I see, I had completely forgotten about the other package.

**Comment by xylar** [comment]
@jasonb5, I see that you'r only now becoming a maintainer of this package so you can't merge this PR.  Let me know when this is ready to merge.

**Comment by jasonb5** [comment]
@xylar This is ready to merge. Thanks!

**Pull request merged**
