### PR TITLE
Rebuild jasper4 0 1 h6ebf4a

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

closes #45

### CODE REVIEW

**Comment by xylar** [comment]
@zklaus, this looks great!  Any reason not to merge this an close #45?

**Comment by zklaus** [comment]
None that I can see. I'll add myself to the maintainers. If you prefer that doesn't happen, feel free to just plug the patch to the other PR.

**Comment by xylar** [comment]
@zklaus, you are always welcome as a maintainer! Thank you!

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by xylar — APPROVED** [review]

**Pull request merged**
