### PR TITLE
bump build number to 4 for 3.1.2

### PR DESCRIPTION
**Pull request by muryanto1**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by doutriaux1** [comment]
@muryanto1 either install conda-smithy in your local conda ot try from a branch on conda-froge repo

**Comment by muryanto1** [comment]
> @muryanto1 either install conda-smithy in your local conda ot try from a branch on conda-froge repo

$ conda smithy recipe-lint
/Users/muryanto1/work/libcdms.09.13/libcdms-feedstock/recipe is in fine form

**Comment by muryanto1** [comment]
I think I need the PR to be approved.

**Review by doutriaux1 — APPROVED** [review]

**Comment by doutriaux1** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
